import {cookies} from 'next/headers';
import {env} from 'cloudflare:workers';
import {bucket,currentUser,db,fail,issueSession,ok,password,sha,validPhone,verifyPassword} from '@/lib';
const asText=(x:unknown)=>typeof x==='string'?x.trim():'';
const err=(e:unknown)=>{console.error(e);return fail('ไม่สามารถดำเนินการได้ กรุณาลองใหม่อีกครั้ง',500)};
async function auth(){return await currentUser()}
async function reportAccess(id:number,u:{id:number;role:string}){return db().prepare('SELECT * FROM reports WHERE id=? AND (reporter_user_id=? OR ?=\'Admin\')').bind(id,u.id,u.role).first<any>()}
export async function GET(req:Request,{params}:{params:Promise<{path?:string[]}>}){try{const p=(await params).path||[];const u=await auth();if(p[0]==='me')return ok({user:u});if(p[0]==='search'){const q=new URL(req.url).searchParams.get('q')?.trim()||'';if(q.length<2)return ok({results:[]});const like=`%${q}%`;const rows=await db().prepare(`SELECT DISTINCT r.id,r.status,r.created_at,r.damage_amount,s.first_name,s.last_name FROM reports r JOIN suspects s ON s.id=r.suspect_id LEFT JOIN suspect_phones ph ON ph.suspect_id=s.id LEFT JOIN bank_accounts b ON b.suspect_id=s.id WHERE r.status='Approved' AND (s.first_name LIKE ? OR s.last_name LIKE ? OR (s.first_name || ' ' || s.last_name) LIKE ? OR ph.phone_number LIKE ? OR b.account_number LIKE ?) ORDER BY r.created_at DESC LIMIT 50`).bind(like,like,like,like,like).all();return ok({results:rows.results})}
if(!u)return fail('กรุณาเข้าสู่ระบบ',401);
if(p[0]==='admin-setup'){const admin=await db().prepare("SELECT id FROM users WHERE role='Admin' LIMIT 1").first();return ok({available:!admin&&!!env.ADMIN_SETUP_CODE})}
if(p[0]==='reports'&&p[1]){const id=Number(p[1]);const report=await reportAccess(id,u);if(!report)return fail('ไม่พบรายการ',404);const [suspect,phones,accounts,files,logs]=await Promise.all([db().prepare('SELECT * FROM suspects WHERE id=?').bind(report.suspect_id).first(),db().prepare('SELECT * FROM suspect_phones WHERE suspect_id=?').bind(report.suspect_id).all(),db().prepare('SELECT * FROM bank_accounts WHERE suspect_id=?').bind(report.suspect_id).all(),db().prepare('SELECT id,type,file_name,uploaded_at FROM evidence WHERE report_id=?').bind(id).all(),db().prepare('SELECT l.*,u.full_name AS admin_name FROM admin_logs l JOIN users u ON u.id=l.admin_user_id WHERE report_id=? ORDER BY l.id DESC').bind(id).all()]);return ok({report,suspect,phones:phones.results,accounts:accounts.results,files:files.results,logs:logs.results})}
if(p[0]==='reports'){const rows=await db().prepare(`SELECT r.id,r.incident_date,r.damage_amount,r.status,r.created_at,s.first_name,s.last_name,u.full_name AS reporter_name FROM reports r JOIN suspects s ON s.id=r.suspect_id JOIN users u ON u.id=r.reporter_user_id WHERE r.reporter_user_id=? OR ?='Admin' ORDER BY r.id DESC LIMIT 100`).bind(u.id,u.role).all();return ok({reports:rows.results})}
if(p[0]==='users'&&u.role==='Admin'){const x=await db().prepare('SELECT id,full_name,phone,role,created_at FROM users ORDER BY id DESC LIMIT 100').all();return ok({users:x.results})}
if(p[0]==='suspects'){const q=new URL(req.url).searchParams.get('q')||'';const x=await db().prepare('SELECT id,first_name,last_name FROM suspects WHERE first_name LIKE ? OR last_name LIKE ? ORDER BY id DESC LIMIT 20').bind('%'+q+'%','%'+q+'%').all();return ok({suspects:x.results})}
if(p[0]==='evidence'&&p[1]){const row=await db().prepare('SELECT * FROM evidence WHERE id=?').bind(Number(p[1])).first<any>();if(!row||!await reportAccess(row.report_id,u))return fail('ไม่พบหลักฐาน',404);const object=await bucket().get(row.file_key);if(!object)return fail('ไม่พบไฟล์',404);return new Response(object.body,{headers:{'Content-Type':row.content_type,'Content-Disposition':`attachment; filename="evidence-${row.id}"`,'X-Content-Type-Options':'nosniff'}})}
return fail('ไม่พบข้อมูล',404)}catch(e){return err(e)}}
export async function POST(req:Request,{params}:{params:Promise<{path?:string[]}>}){try{const p=(await params).path||[];
if(p[0]==='register'||p[0]==='login'){const b=await req.json();const phone=asText(b.phone),pass=asText(b.password);if(!validPhone(phone)||pass.length<8)return fail('กรุณากรอกเบอร์ 10 หลัก และรหัสผ่านอย่างน้อย 8 ตัว');if(p[0]==='register'){const fullName=asText(b.fullName);if(!fullName)return fail('กรุณากรอกชื่อและนามสกุล');const exists=await db().prepare('SELECT id FROM users WHERE phone=?').bind(phone).first();if(exists)return fail('เบอร์นี้มีบัญชีแล้ว');const result=await db().prepare('INSERT INTO users(full_name,phone,password_hash,role) VALUES(?,?,?,?)').bind(fullName,phone,await password(pass),'User').run();await issueSession(Number(result.meta.last_row_id));return ok({success:true})}const row=await db().prepare('SELECT id,password_hash FROM users WHERE phone=?').bind(phone).first<{id:number;password_hash:string}>();if(!row||!await verifyPassword(pass,row.password_hash))return fail('เบอร์โทรศัพท์หรือรหัสผ่านไม่ถูกต้อง',401);await issueSession(row.id);return ok({success:true})}
const u=await auth();if(!u)return fail('กรุณาเข้าสู่ระบบ',401);
if(p[0]==='admin-setup'){const code=asText((await req.json()).code);if(!env.ADMIN_SETUP_CODE||!code||code.length!==env.ADMIN_SETUP_CODE.length||await sha(code)!==await sha(env.ADMIN_SETUP_CODE))return fail('รหัสตั้งค่าไม่ถูกต้อง',403);const result=await db().prepare("UPDATE users SET role='Admin' WHERE id=? AND NOT EXISTS (SELECT 1 FROM users WHERE role='Admin')").bind(u.id).run();if(!result.meta.changes)return fail('ระบบมีแอดมินแล้ว',409);return ok({success:true})}
if(p[0]==='logout'){const token=(await cookies()).get('session')?.value;if(token)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(token)).run();(await cookies()).delete('session');return ok({success:true})}
if(p[0]==='users'&&p[1]&&p[2]==='role'){if(u.role!=='Admin')return fail('เฉพาะผู้ดูแลระบบ',403);const target=Number(p[1]),b=await req.json(),role=asText(b.role);if(!['Admin','User'].includes(role))return fail('สิทธิ์ไม่ถูกต้อง');if(target===u.id&&role!=='Admin')return fail('ไม่สามารถลดสิทธิ์บัญชีตนเอง');const result=await db().prepare('UPDATE users SET role=? WHERE id=?').bind(role,target).run();if(!result.meta.changes)return fail('ไม่พบผู้ใช้',404);return ok({success:true})}
if(p[0]==='reports'&&p[1]&&p[2]==='status'){if(u.role!=='Admin')return fail('เฉพาะผู้ดูแลระบบ',403);const id=Number(p[1]),b=await req.json(),status=asText(b.status),remark=asText(b.remark);if(!['Pending','Approved','Rejected'].includes(status))return fail('สถานะไม่ถูกต้อง');const old=await db().prepare('SELECT id FROM reports WHERE id=?').bind(id).first();if(!old)return fail('ไม่พบเคส',404);await db().batch([db().prepare('UPDATE reports SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,id),db().prepare('INSERT INTO admin_logs(report_id,admin_user_id,action_type,remark) VALUES(?,?,?,?)').bind(id,u.id,status,remark)]);return ok({success:true})}
if(p[0]==='reports'){const b=await req.json();const suspectId=Number(b.suspectId),date=asText(b.incidentDate),details=asText(b.details),amount=Number(b.damageAmount);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(amount)||amount<0||!details||details.length>5000)return fail('กรุณากรอกวันที่ ยอดเสียหาย และรายละเอียดให้ครบ');let sid=suspectId;if(sid){const s=await db().prepare('SELECT id FROM suspects WHERE id=?').bind(sid).first();if(!s)return fail('ไม่พบบุคคลที่เลือก')}else{const first=asText(b.firstName),last=asText(b.lastName);if(!first||!last)return fail('กรุณากรอกชื่อและนามสกุลบุคคลต้องสงสัย');const result=await db().prepare('INSERT INTO suspects(first_name,last_name,line_id) VALUES(?,?,?)').bind(first,last,asText(b.lineId)||null).run();sid=Number(result.meta.last_row_id)}const phone=asText(b.suspectPhone),account=asText(b.accountNumber),accountName=asText(b.accountName),bank=asText(b.bankName);if(phone&&!validPhone(phone))return fail('เบอร์บุคคลต้องสงสัยต้องเป็นตัวเลข 10 หลัก');if(account&&(!/^\d{5,20}$/.test(account)||!accountName||!bank))return fail('กรุณากรอกเลขบัญชีเป็นตัวเลข พร้อมชื่อบัญชีและธนาคาร');const result=await db().prepare('INSERT INTO reports(reporter_user_id,suspect_id,incident_date,damage_amount,details) VALUES(?,?,?,?,?)').bind(u.id,sid,date,amount,details).run();const id=Number(result.meta.last_row_id);if(phone)await db().prepare('INSERT INTO suspect_phones(suspect_id,phone_number) VALUES(?,?)').bind(sid,phone).run();if(account)await db().prepare('INSERT INTO bank_accounts(suspect_id,account_number,account_name,bank_name) VALUES(?,?,?,?)').bind(sid,account,accountName,bank).run();return ok({id})}
if(p[0]==='evidence'&&p[1]){const id=Number(p[1]);if(!await reportAccess(id,u))return fail('ไม่พบเคส',404);const form=await req.formData(),file=form.get('file'),type=asText(form.get('type'));if(!(file instanceof File)||file.size===0||file.size>5*1024*1024)return fail('ไฟล์ต้องมีขนาดไม่เกิน 5 MB');if(!['Slip','Chat','Image','Other'].includes(type))return fail('ประเภทหลักฐานไม่ถูกต้อง');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))return fail('รองรับ JPG, PNG, WebP หรือ PDF เท่านั้น');const key=`reports/${id}/${crypto.randomUUID()}`;await bucket().put(key,file.stream(),{httpMetadata:{contentType:file.type}});await db().prepare('INSERT INTO evidence(report_id,type,file_key,file_name,content_type) VALUES(?,?,?,?,?)').bind(id,type,key,file.name.slice(0,200),file.type).run();return ok({success:true})}
return fail('ไม่พบข้อมูล',404)}catch(e){return err(e)}}
